language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install black nose coveralls
# command to run tests
script:
    - python setup.py install
    - black --line-length 120 .
    - nosetests -vv --with-coverage --cover-inclusive --cover-package=tanner
after_success: coveralls
